project_id = "wouwaifqgzlwnkvpnndg"

[functions.law-proxy]
verify_jwt = false

[functions.law-search]
verify_jwt = false

[functions.advanced-precedent-search]
verify_jwt = false

[functions.precedent-detail]
verify_jwt = false